### PR TITLE
parallel hashing and partitioning

### PR DESCRIPTION
**Pull request by stefanfred**

### CODE REVIEW

**Comment by stefanfred** [comment]
This pr aims at improving performance for large machines e.g. 64 cores

**Comment by jermp** [comment]
Oh nice! Can you please resolve the conflict first?

**Comment by jermp** [comment]
Hi @stefanfred, what does this PR exactly do?
The hashing and partitioning takes a tiny fraction of the whole construction runtime.
The problem with this PR is that it introduces a hard-to-resolve dependency: Intel TBB.
I'm skeptic about introducing such dependency in PTHash, especially as PTHash is used
in several other projects. For this reason, I've only relied on C++ native threads.
Wouldn't you agree?

CC @ByteHamster

**Comment by ByteHamster** [comment]
> The hashing and partitioning takes a tiny fraction of the whole construction runtime

On our 64 core machine we got the following timings:

partitioning: 4.13375 [sec]
mapping+ordering: 0.168182 [sec]
searching: 0.812384 [sec]
encoding: 0.867332 [sec]

Without this change, the overall multi-threaded speedup of the construction was 5, while it was around 20 for most other competitors.

**Comment by stefanfred** [comment]
We observed that PTHash is severely bottlenecked on larger machines by the sequential partitioning step. I could look for a parallel sort library which does not depend on TBB or OpenMP. Would that be fine with you?

@jermp 
@ByteHamster

**Comment by jermp** [comment]
Oh ok, so when using many threads the search is well parallelized so the sequential fraction becomes significant.
Makes sense. When I said that fraction was tiny, I was referring to Fig. 5b from the current version of the paper.
Thanks for handling this!

Then I guess OpenMP should be fine, but definitely not TBB please :)
Even better if we only use native C++ threads.

**Comment by stefanfred** [comment]
i was not able to find a parallel sorting library which does not rely on tbb and is about as fast as ipsra.
I am not certain as to how to proceed.
We only need the parallel partitioning for a table in the appendix were we use a 64 core machine.
One option is to use ipsra on a seperate branch. Another option is to leave out the table. 

@jermp 
@ByteHamster

**Comment by stefanfred** [comment]
Ok. #47 should do it

**Pull request merged**
