### PR TITLE
Add partitioned_phf::swap and partitioned_phf::visit

### PR DESCRIPTION
**Pull request by progval**
This mirrors single_phf

### CODE REVIEW

**Comment by jermp** [comment]
While this makes the code symmetric, we don't actually need this.
So I'm reluctant to add useless code. Thanks anyway!

**Comment by progval** [comment]
Should I send a PR to remove them from `internal_memory_builder_single_phf` too?

**Comment by jermp** [comment]
No, because we need them there for the external-memory construction algorithm :)

**Comment by progval** [comment]
Ah, I see

**Pull request closed without merging**
